import type { ImageGenerator, MediaStorageService } from "@agent/media";

import type { Tool } from "../tool.js";

export interface GenerateImageToolInput {
  prompt: string;
  aspectRatio?: "1:1" | "4:5" | "9:16" | "16:9";
  /** Identify the object without deriving a key from anything model-produced. */
  accountId: string;
  contentId: string;
  assetId: string;
}

export interface GenerateImageToolOutput {
  storageKey: string;
  url: string;
  mimeType: string;
  provider: string;
  storageProvider: string;
  sizeBytes: number;
  providerAssetId?: string;
  width?: number;
  height?: number;
  /** True when the generated bytes were re-encoded to JPEG on the way to storage. */
  converted: boolean;
  originalMimeType: string;
}

/**
 * The only place that calls a real ImageGenerator + persists bytes — routed
 * through the policy layer (kill switch, DailyGenerationLimitPolicy) exactly
 * like publishPost, so media generation can never bypass cost/safety
 * controls.
 *
 * Storage specifics (R2 vs local disk, key layout, JPEG conversion) live
 * behind MediaStorageService; this tool only knows it gets back a key, a
 * public URL and some metadata.
 */
export class GenerateImageTool implements Tool<GenerateImageToolInput, GenerateImageToolOutput> {
  readonly name = "generateImage";
  readonly description = "Generate a real image asset for a piece of content and persist it to object storage.";

  constructor(
    private readonly imageGenerator: ImageGenerator,
    private readonly mediaStorage: MediaStorageService,
  ) {}

  async execute(input: GenerateImageToolInput) {
    const result = await this.imageGenerator.generate({ prompt: input.prompt, aspectRatio: input.aspectRatio });

    // Converts to JPEG when needed: Instagram accepts JPEG only, and the mock
    // generator emits SVG. Storing the SVG under a .jpg name would just move
    // the failure to Meta, where it is far harder to diagnose.
    const stored = await this.mediaStorage.storeImage({
      accountId: input.accountId,
      contentId: input.contentId,
      assetId: input.assetId,
      data: result.imageData,
      mimeType: result.mimeType,
    });

    return {
      success: true,
      data: {
        storageKey: stored.objectKey,
        url: stored.publicUrl,
        mimeType: stored.contentType,
        provider: result.provider,
        storageProvider: stored.storageProvider,
        sizeBytes: stored.size,
        providerAssetId: result.providerAssetId,
        // Post-conversion dimensions win: they describe the object actually stored.
        width: stored.width ?? result.width,
        height: stored.height ?? result.height,
        converted: stored.converted,
        originalMimeType: stored.originalMimeType,
      },
    };
  }
}
